export const USER_ROLES = {
  SUPER_ADMIN: 'super_admin',
  FLEET_MANAGER: 'fleet_manager',
  DISPATCHER: 'dispatcher',
  DRIVER: 'driver',
  MECHANIC: 'mechanic',
};

export const ROLE_LABELS = {
  [USER_ROLES.SUPER_ADMIN]: 'Super Admin',
  [USER_ROLES.FLEET_MANAGER]: 'Fleet Manager',
  [USER_ROLES.DISPATCHER]: 'Dispatcher',
  [USER_ROLES.DRIVER]: 'Driver',
  [USER_ROLES.MECHANIC]: 'Mechanic',
};

export const PERMISSIONS = {
  // Users & Admin
  MANAGE_USERS: 'manage_users',
  MANAGE_ROLES: 'manage_roles',
  VIEW_ADMIN_PANEL: 'view_admin_panel',

  // Vehicles
  VIEW_VEHICLES: 'view_vehicles',
  CREATE_VEHICLES: 'create_vehicles',
  UPDATE_VEHICLES: 'update_vehicles',
  DELETE_VEHICLES: 'delete_vehicles',
  ASSIGN_VEHICLES: 'assign_vehicles',

  // Drivers
  VIEW_DRIVERS: 'view_drivers',
  CREATE_DRIVERS: 'create_drivers',
  UPDATE_DRIVERS: 'update_drivers',
  DELETE_DRIVERS: 'delete_drivers',
  ASSIGN_DRIVERS: 'assign_drivers',

  // Trips & Routes
  VIEW_TRIPS: 'view_trips',
  CREATE_TRIPS: 'create_trips',
  UPDATE_TRIPS: 'update_trips',
  REVIEW_TRIPS: 'review_trips',
  DELETE_TRIPS: 'delete_trips',
  MANAGE_ROUTES: 'manage_routes',

  // GPS & Tracking
  VIEW_TRACKING: 'view_tracking',
  MANAGE_GEOFENCES: 'manage_geofences',

  // Fuel
  VIEW_FUEL: 'view_fuel',
  MANAGE_FUEL: 'manage_fuel',

  // Maintenance
  VIEW_MAINTENANCE: 'view_maintenance',
  MANAGE_MAINTENANCE: 'manage_maintenance',
  ASSIGN_WORK_ORDERS: 'assign_work_orders',

  // Documents
  VIEW_DOCUMENTS: 'view_documents',
  MANAGE_DOCUMENTS: 'manage_documents',

  // Reports & Analytics
  VIEW_REPORTS: 'view_reports',
  EXPORT_REPORTS: 'export_reports',
  VIEW_ANALYTICS: 'view_analytics',

  // Alerts & Notifications
  VIEW_ALERTS: 'view_alerts',
  MANAGE_ALERTS: 'manage_alerts',

  // Settings
  MANAGE_SETTINGS: 'manage_settings',
};

export const ROLE_PERMISSIONS = {
  [USER_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [USER_ROLES.FLEET_MANAGER]: [
    PERMISSIONS.VIEW_VEHICLES,
    PERMISSIONS.CREATE_VEHICLES,
    PERMISSIONS.UPDATE_VEHICLES,
    PERMISSIONS.DELETE_VEHICLES,
    PERMISSIONS.ASSIGN_VEHICLES,
    PERMISSIONS.VIEW_DRIVERS,
    PERMISSIONS.CREATE_DRIVERS,
    PERMISSIONS.UPDATE_DRIVERS,
    PERMISSIONS.DELETE_DRIVERS,
    PERMISSIONS.ASSIGN_DRIVERS,
    PERMISSIONS.VIEW_TRIPS,
    PERMISSIONS.CREATE_TRIPS,
    PERMISSIONS.UPDATE_TRIPS,
    PERMISSIONS.REVIEW_TRIPS,
    PERMISSIONS.DELETE_TRIPS,
    PERMISSIONS.MANAGE_ROUTES,
    PERMISSIONS.VIEW_TRACKING,
    PERMISSIONS.MANAGE_GEOFENCES,
    PERMISSIONS.VIEW_FUEL,
    PERMISSIONS.MANAGE_FUEL,
    PERMISSIONS.VIEW_MAINTENANCE,
    PERMISSIONS.MANAGE_MAINTENANCE,
    PERMISSIONS.ASSIGN_WORK_ORDERS,
    PERMISSIONS.VIEW_DOCUMENTS,
    PERMISSIONS.MANAGE_DOCUMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.MANAGE_ALERTS,
    PERMISSIONS.MANAGE_SETTINGS,
  ],

  [USER_ROLES.DISPATCHER]: [
    PERMISSIONS.VIEW_VEHICLES,
    PERMISSIONS.VIEW_DRIVERS,
    PERMISSIONS.ASSIGN_DRIVERS,
    PERMISSIONS.ASSIGN_VEHICLES,
    PERMISSIONS.VIEW_TRIPS,
    PERMISSIONS.CREATE_TRIPS,
    PERMISSIONS.UPDATE_TRIPS,
    PERMISSIONS.REVIEW_TRIPS,
    PERMISSIONS.MANAGE_ROUTES,
    PERMISSIONS.VIEW_TRACKING,
    PERMISSIONS.VIEW_FUEL,
    PERMISSIONS.VIEW_ALERTS,
    PERMISSIONS.VIEW_REPORTS,
  ],

  [USER_ROLES.DRIVER]: [
    PERMISSIONS.VIEW_TRIPS,
    PERMISSIONS.UPDATE_TRIPS,
    PERMISSIONS.VIEW_ALERTS,
  ],

  [USER_ROLES.MECHANIC]: [
    PERMISSIONS.VIEW_VEHICLES,
    PERMISSIONS.VIEW_MAINTENANCE,
    PERMISSIONS.MANAGE_MAINTENANCE,
    PERMISSIONS.ASSIGN_WORK_ORDERS,
    PERMISSIONS.VIEW_ALERTS,
  ],
};

export default { USER_ROLES, ROLE_LABELS, PERMISSIONS, ROLE_PERMISSIONS };
